build-DemoSQSSenderFunction:
#	mvn clean package -P native-image
	chmod +x target/hello-world
	cp target/hello-world $(ARTIFACTS_DIR) # (ARTIFACTS_DIR --> https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/custom_make/DESIGN.md#implementation)
	chmod +x src/main/config/bootstrap
	cp src/main/config/bootstrap $(ARTIFACTS_DIR)


build-DemoSQSConsumerFunction:
#	mvn clean package -P native-image
	chmod +x target/hello-world
	cp target/hello-world $(ARTIFACTS_DIR) # (ARTIFACTS_DIR --> https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/custom_make/DESIGN.md#implementation)
	chmod +x src/main/config/bootstrap
	cp src/main/config/bootstrap $(ARTIFACTS_DIR)

build-DemoKinesisSenderFunction:
#	mvn clean package -P native-image
	chmod +x target/hello-world
	cp target/hello-world $(ARTIFACTS_DIR) # (ARTIFACTS_DIR --> https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/custom_make/DESIGN.md#implementation)
	chmod +x src/main/config/bootstrap
	cp src/main/config/bootstrap $(ARTIFACTS_DIR)

build-DemoKinesisConsumerFunction:
#	mvn clean package -P native-image
	chmod +x target/hello-world
	cp target/hello-world $(ARTIFACTS_DIR) # (ARTIFACTS_DIR --> https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/custom_make/DESIGN.md#implementation)
	chmod +x src/main/config/bootstrap
	cp src/main/config/bootstrap $(ARTIFACTS_DIR)

build-DemoDynamoDBWriter:
#	mvn clean package -P native-image
	chmod +x target/hello-world
	cp target/hello-world $(ARTIFACTS_DIR) # (ARTIFACTS_DIR --> https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/custom_make/DESIGN.md#implementation)
	chmod +x src/main/config/bootstrap
	cp src/main/config/bootstrap $(ARTIFACTS_DIR)

build-DemoDynamoDBStreamsConsumerFunction:
#	mvn clean package -P native-image
	chmod +x target/hello-world
	cp target/hello-world $(ARTIFACTS_DIR) # (ARTIFACTS_DIR --> https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/custom_make/DESIGN.md#implementation)
	chmod +x src/main/config/bootstrap
	cp src/main/config/bootstrap $(ARTIFACTS_DIR)